### ISSUE TITLE
Playing interrupts when 2 apps with analytics listeners are active on Android 8.1

### ISSUE THREAD

**Issue by snoopy112** [z-huang/InnerTune#318]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/z-huang/music/releases/latest).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Install release version
2. Install debug version (or ViMusic)
3. Start playing from one app
4. Start playing from other app

### Expected behavior

Playing without interruptions every 2-3 seconds. This happens due to Analytics Listener (addAnalyticsListener(PlaybackStatsListener(false, this@SongPlayer))), but this listener needed for caching tracks... Is it possible to somehow fix this feature?

### Actual behavior

Playing without interruptions.

### Logs

D/AudioTrack: matchPkgName() the opPkg:com.finestandroid.soundgenerator
D/AudioTrack: matchPkgName() the opPkg:com.netease.cloudmusic
D/AudioTrack: matchPkgName() the opPkg:com.tencent.qqmusic
D/AudioTrack: matchPkgName() the opPkg:com.jetappfactory.jetaudioplus
D/AudioTrack: Client defaulted notificationFrames to 6000 for frameCount 12000
E/AudioTrack-JNI: Error -32 during AudioTrack native read
E/MediaCodecAudioRenderer: Audio sink error
      com.google.android.exoplayer2.audio.AudioSink$WriteException: AudioTrack write failed: -6
        at com.google.android.exoplayer2.audio.DefaultAudioSink.writeBuffer(DefaultAudioSink.java:1174)
        at com.google.android.exoplayer2.audio.DefaultAudioSink.processBuffers(DefaultAudioSink.java:1098)
        at com.google.android.exoplayer2.audio.DefaultAudioSink.handleBuffer(DefaultAudioSink.java:1030)
        at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.processOutputBuffer(MediaCodecAudioRenderer.java:703)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1894)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:792)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:989)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:490)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:164)
        at android.os.HandlerThread.run(HandlerThread.java:65)
W/ExoPlayerImplInternal: Recoverable renderer error
      com.google.android.exoplayer2.ExoPlaybackException: MediaCodecAudioRenderer error, index=1, format=Format(1, null, null, audio/opus, null, -1, en, [-1, -1, -1.0], [2, 48000]), format_supported=YES
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:566)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:164)
        at android.os.HandlerThread.run(HandlerThread.java:65)
     Caused by: com.google.android.exoplayer2.audio.AudioSink$WriteException: AudioTrack write failed: -6
        at com.google.android.exoplayer2.audio.DefaultAudioSink.writeBuffer(DefaultAudioSink.java:1174)
        at com.google.android.exoplayer2.audio.DefaultAudioSink.processBuffers(DefaultAudioSink.java:1098)
        at com.google.android.exoplayer2.audio.DefaultAudioSink.handleBuffer(DefaultAudioSink.java:1030)
        at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.processOutputBuffer(MediaCodecAudioRenderer.java:703)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1894)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:792)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:989)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:490)
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.os.HandlerThread.run(HandlerThread.java:65) 
I/OMXClient: Treble IOmx obtained
I/ACodec: codec does not support config priority (err -2147483648)
I/ACodec: codec does not support config priority (err -2147483648)
I/ACodec: codec does not support config operating rate (err -2147483648)
W/ExtendedACodec: Failed to get extension for extradata parameter
W/SQLiteConnectionPool: A SQLiteConnection object for database '/data/user/0/com.zionhuang.music.debug/databases/exoplayer_internal.db' was leaked!  Please fix your application to end transactions in progress properly and to close the database when it is no longer needed.

### Music version

0.4.2

### Android version

Android 8.1

**Comment by z-huang** [comment]
Can't reproduce. Is this Android-version specific?

**Comment by snoopy112** [comment]
Maybe, unfortunately I'm not an expert in android apps. I've tested on Hiby R5 player.

**Comment by z-huang** [comment]
I tried in an Android 8.1 emulator and couldn't reproduce.

**Comment by snoopy112** [comment]
Ok, maybe it's a device problem...
