### ISSUE TITLE
App sometimes crashes when clicking on a song

### ISSUE THREAD

**Issue by chtheilist** [z-huang/InnerTune#321]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/z-huang/music/releases/latest).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Play several songs in explore or in library. (the issue appears to happen randomly)

### Expected behavior

The song should always play. 

### Actual behavior

Song crashes the app

### Logs

```
type: crash
osVersion: google/bluejay/bluejay:13/TP1A.221005.003/2022101500:user/release-keys
package: com.zionhuang.music:13
process: com.zionhuang.music

java.lang.IllegalStateException: Slider value(208564.0) must be greater or equal to valueFrom(0.0), and lower or equal to valueTo(158000.0)
	at n6.c.u(SourceFile:201)
	at n6.c.onDraw(SourceFile:8)
	at android.view.View.draw(View.java:23195)
	at android.view.View.updateDisplayListIfDirty(View.java:22062)
	at android.view.View.draw(View.java:22926)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4529)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)
	at android.view.View.updateDisplayListIfDirty(View.java:22053)
	at android.view.View.draw(View.java:22926)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4529)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)
	at android.view.View.updateDisplayListIfDirty(View.java:22053)
	at android.view.View.draw(View.java:22926)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4529)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.drawChild(Unknown Source:13)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)
	at android.view.View.draw(View.java:23198)
	at android.view.View.updateDisplayListIfDirty(View.java:22062)
	at android.view.View.draw(View.java:22926)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4529)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.drawChild(Unknown Source:13)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)
	at android.view.View.updateDisplayListIfDirty(View.java:22053)
	at android.view.View.draw(View.java:22926)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4529)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)
	at android.view.View.updateDisplayListIfDirty(View.java:22053)
	at android.view.View.draw(View.java:22926)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4529)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)
	at android.view.View.updateDisplayListIfDirty(View.java:22053)
	at android.view.View.draw(View.java:22926)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4529)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)
	at android.view.View.updateDisplayListIfDirty(View.java:22053)
	at android.view.View.draw(View.java:22926)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4529)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)
	at android.view.View.updateDisplayListIfDirty(View.java:22053)
	at android.view.View.draw(View.java:22926)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4529)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)
	at android.view.View.draw(View.java:23198)
	at com.android.internal.policy.DecorView.draw(DecorView.java:819)
	at android.view.View.updateDisplayListIfDirty(View.java:22062)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:682)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:688)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:786)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:4579)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4290)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3517)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2286)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8948)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1231)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
	at android.view.Choreographer.doCallbacks(Choreographer.java:899)
	at android.view.Choreographer.doFrame(Choreographer.java:832)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7904)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)

```

### Music version

0.4.2

### Android version

Android 13

### Additional information

After playing a few songs and using the app normally, any particular song randomly makes the app crash. I have documented the crash from the crash report provided by my android system.

**Comment by JPGuillemin** [comment]
confirmed (yesterday with latest DEBUG)

**Comment by z-huang** [comment]
Is there any reliable way to reproduce? I didn't find it in my phone.

**Comment by z-huang** [comment]
https://github.com/z-huang/InnerTune/blob/94e3e4f0900082d6d0556c1c2e74149be3f09d75/app/src/main/java/com/zionhuang/music/ui/fragments/BottomControlsFragment.kt#L100

This is where the slider update its value. I coerce the value between the `valueFrom` and `valueTo`.🤔

**Comment by z-huang** [comment]
Then I'll close the issue until someone who can reproduce reopen it.
