### ISSUE TITLE
Crash on Bottom sheet view

### ISSUE THREAD

**Issue by shuvashish76** [z-huang/InnerTune#361]
**Steps to reproduce:**

1. Click on 3dot menu of any song to view bottom sheet
2. Click "recent apps" or "home" button from device navigation bar
3. App crashes

**Crash logs:**

```
FATAL EXCEPTION: main
Process: com.zionhuang.music, PID: 5221
java.lang.RuntimeException: Parcelable encountered IOException writing serializable object (name = x7.g$a$a)
	at android.os.Parcel.writeSerializable(Parcel.java:1831)
	at android.os.Parcel.writeValue(Parcel.java:1779)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:846)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1542)
	at android.os.Bundle.writeToParcel(Bundle.java:1232)
	at android.os.Parcel.writeBundle(Parcel.java:886)
	at androidx.fragment.app.m0.writeToParcel(Unknown Source:47)
	at android.os.Parcel.writeParcelable(Parcel.java:1800)
	at android.os.Parcel.writeValue(Parcel.java:1706)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:846)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1542)
	at android.os.Bundle.writeToParcel(Bundle.java:1232)
	at android.os.Parcel.writeBundle(Parcel.java:886)
	at android.os.Parcel.writeValue(Parcel.java:1697)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:846)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1542)
	at android.os.Bundle.writeToParcel(Bundle.java:1232)
	at android.os.Parcel.writeBundle(Parcel.java:886)
	at android.os.Parcel.writeValue(Parcel.java:1697)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:846)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1542)
	at android.os.Bundle.writeToParcel(Bundle.java:1232)
	at android.os.Parcel.writeBundle(Parcel.java:886)
	at android.os.Parcel.writeValue(Parcel.java:1697)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:846)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1542)
	at android.os.Bundle.writeToParcel(Bundle.java:1232)
	at android.app.IActivityManager$Stub$Proxy.activityStopped(IActivityManager.java:4604)
	at android.app.ActivityThread$StopInfo.run(ActivityThread.java:3937)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6518)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
Caused by: java.io.NotSerializableException: f7.s
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1233)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1597)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1558)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1481)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1227)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:347)
	at android.os.Parcel.writeSerializable(Parcel.java:1826)
	... 35 more
```

**Device details:**
Model: Lenovo TB-8704X
Android: 8.1.0
App version: **0.4.2 (13)**

**Comment by z-huang** [comment]
Not an easy fix currently. Migrating to Compose may solve the issue.
