### ISSUE TITLE
Fatal Crash when selecting multiple songs in the Songs TAB

### ISSUE THREAD

**Issue by JPGuillemin** [z-huang/InnerTune#363]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/z-huang/InnerTune/releases/latest).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Go to Songs tab
Long press on a song to Select it : selected ok
Long press on another song to add it to selection : fatal CRASH
App has to be restarted

### Expected behavior

Selecting several songs to download them or deleted them

### Actual behavior

FATAL CRASH

### Logs

FATAL EXCEPTION: main
Process: com.zionhuang.music.debug, PID: 7069
android.content.res.Resources$NotFoundException: Plural resource ID #0x7f120005 quantity=2 item=other
at android.content.res.ResourcesImpl.getQuantityText(ResourcesImpl.java:331)
at android.content.res.Resources.getQuantityText(Resources.java:537)
at android.content.res.Resources.getQuantityString(Resources.java:613)
at com.zionhuang.music.utils.ActionModeSelectionObserver.onItemStateChanged(ActionModeSelectionObserver.kt:46)
at androidx.recyclerview.selection.DefaultSelectionTracker.notifyItemStateChanged(DefaultSelectionTracker.java:445)
at androidx.recyclerview.selection.DefaultSelectionTracker.select(DefaultSelectionTracker.java:235)
at androidx.recyclerview.selection.Motijava-scriptHandler.selectItem(Motijava-scriptHandler.java:59)
at androidx.recyclerview.selection.TouchInputHandler.onSingleTapUp(TouchInputHandler.java:99)
at androidx.recyclerview.selection.GestureRouter.onSingleTapUp(GestureRouter.java:86)
at android.view.GestureDetector.onTouchEvent(GestureDetector.java:748)
at androidx.recyclerview.selection.GestureDetectorWrapper.onInterceptTouchEvent(GestureDetectorWrapper.java:54)
at androidx.recyclerview.widget.RecyclerView.findInterceptingOnItemTouchListener(RecyclerView.java:3286)
at androidx.recyclerview.widget.RecyclerView.onInterceptTouchEvent(RecyclerView.java:3305)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2661)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3131)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2812)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3131)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2812)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3131)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2812)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3131)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2812)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3131)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2812)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3131)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2812)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3131)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2812)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3131)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2812)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3131)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2812)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3131)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2812)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3131)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2812)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3131)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2812)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3131)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2812)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3131)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2812)
at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:562)
at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1895)
at android.app.Activity.dispatchTouchEvent(Activity.java:4319)
at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:70)
at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:520)
at android.view.View.dispatchPointerEvent(View.java:15130)
at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6659)
at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6447)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5888)
at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5945)
at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5911)
at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6076)
at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5919)
at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6133)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5892)
at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5945)
at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5911)
at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5919)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5892)
at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:8914)
at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8865)
at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:8833)
at android.view.ViewRootImpl$WindowInputEventReceiver.java-scriptEvent(ViewRootImpl.java:9047)
at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:281)
at android.os.MessageQueue.nativePollOnce(Native Method)
at android.os.MessageQueue.next(MessageQueue.java:340)
at android.os.Looper.loopOnce(Looper.java:168)
at android.os.Looper.loop(Looper.java:299)
at android.app.ActivityThread.main(ActivityThread.java:8108)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045) 

### Music version

latest debug

### Android version

12

**Comment by z-huang** [comment]
Can't reproduce. It's better to provide a screen record or logs.

**Comment by JPGuillemin** [comment]
where are the logs ?

**Comment by JPGuillemin** [comment]
impossible to provide a screen record : FATAL CRASH

**Comment by shuvashish76** [comment]
Can't reproduce on my device as well.

> where are the logs ?

Use https://www.f-droid.org/packages/taco.scoop/ any similar app to trace crash of other apps.

**Comment by z-huang** [comment]
Yes.

**Comment by JPGuillemin** [comment]
no way to catch the crash with Taco (needs READ_LOGS and I'm not rooted)

**Comment by shuvashish76** [comment]
This is going slightly offtopic.
@JPGuillemin Follow their [guide](https://github.com/TacoTheDank/Scoop/wiki).

**Comment by JPGuillemin** [comment]
Finally found a way to grant perm, so here's the logs : 

FATAL EXCEPTION: main
Process: com.zionhuang.music.debug, PID: 7069
android.content.res.Resources$NotFoundException: Plural resource ID #0x7f120005 quantity=2 item=other
at android.content.res.ResourcesImpl.getQuantityText(ResourcesImpl.java:331)
at android.content.res.Resources.getQuantityText(Resources.java:537)
at android.content.res.Resources.getQuantityString(Resources.java:613)
at com.zionhuang.music.utils.ActionModeSelectionObserver.onItemStateChanged(ActionModeSelectionObserver.kt:46)
at androidx.recyclerview.selection.DefaultSelectionTracker.notifyItemStateChanged(DefaultSelectionTracker.java:445)
at androidx.recyclerview.selection.DefaultSelectionTracker.select(DefaultSelectionTracker.java:235)
at androidx.recyclerview.selection.Motijava-scriptHandler.selectItem(Motijava-scriptHandler.java:59)
at androidx.recyclerview.selection.TouchInputHandler.onSingleTapUp(TouchInputHandler.java:99)
at androidx.recyclerview.selection.GestureRouter.onSingleTapUp(GestureRouter.java:86)
at android.view.GestureDetector.onTouchEvent(GestureDetector.java:748)
at androidx.recyclerview.selection.GestureDetectorWrapper.onInterceptTouchEvent(GestureDetectorWrapper.java:54)
at androidx.recyclerview.widget.RecyclerView.findInterceptingOnItemTouchListener(RecyclerView.java:3286)
at androidx.recyclerview.widget.RecyclerView.onInterceptTouchEvent(RecyclerView.java:3305)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2661)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3131)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2812)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3131)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2812)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3131)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2812)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3131)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2812)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3131)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2812)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3131)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2812)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3131)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2812)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3131)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2812)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3131)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2812)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3131)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2812)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3131)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2812)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3131)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2812)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3131)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2812)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3131)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2812)
at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:562)
at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1895)
at android.app.Activity.dispatchTouchEvent(Activity.java:4319)
at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:70)
at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:520)
at android.view.View.dispatchPointerEvent(View.java:15130)
at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6659)
at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6447)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5888)
at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5945)
at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5911)
at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6076)
at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5919)
at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6133)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5892)
at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5945)
at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5911)
at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5919)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5892)
at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:8914)
at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8865)
at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:8833)
at android.view.ViewRootImpl$WindowInputEventReceiver.java-scriptEvent(ViewRootImpl.java:9047)
at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:281)
at android.os.MessageQueue.nativePollOnce(Native Method)
at android.os.MessageQueue.next(MessageQueue.java:340)
at android.os.Looper.loopOnce(Looper.java:168)
at android.os.Looper.loop(Looper.java:299)
at android.app.ActivityThread.main(ActivityThread.java:8108)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
