### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by zhouxin886** [z-huang/InnerTune#395]
```
java.lang.IllegalArgumentException: fromIndex(0) > toIndex(-1) 	at java.util.ArrayList.subListRangeCheck(ArrayList.java:1018) 	at java.util.ArrayList.subList(ArrayList.java:1008) 	at x7.h.a(SourceFile:283) 	at x7.h$b.u(Unknown Source:12) 	at va.a.m(Unknown Source:8) 	at ga.i.e(SourceFile:71) 	at ga.i.d(SourceFile:16) 	at ga.i$a.m(SourceFile:25) 	at va.a.m(Unknown Source:31) 	at ga.i.e(SourceFile:71) 	at ga.i.d(SourceFile:16) 	at ga.i$a.m(SourceFile:25) 	at va.a.m(Unknown Source:31) 	at ga.i.e(SourceFile:71) 	at ga.i.d(SourceFile:16) 	at ga.i$a.m(SourceFile:25) 	at va.a.m(Unknown Source:31) 	at ga.i.e(SourceFile:71) 	at ga.i.d(SourceFile:16) 	at ga.i$a.m(SourceFile:25) 	at va.a.m(Unknown Source:31) 	at lb.o0.run(Unknown Source:100) 	at qb.h.run(Unknown Source:12) 	at rb.j.run(Unknown Source:2) 	at rb.a$a.run(SourceFile:82) 
```

**Comment by z-huang** [comment]
Please, use the issue to report a bug. I can't help if you just paste the log without any description.
