### ISSUE TITLE
App crashes caused by viewing non-existent artist

### ISSUE THREAD

**Issue by Sdarfeesh** [z-huang/InnerTune#424]
### Checklist

- [X] I am able to reproduce the bug with the [latest DEBUG version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Play a song by non-existent artist
2. View artist in music player

### Expected behavior

Artist cannot be viewed

### Actual behavior

App crashes

### Screenshots/Screen recordings

https://user-images.githubusercontent.com/50188628/201461459-ec47564c-0b53-4240-ab3f-af9852d9e6d5.mp4

### Logs

```
FATAL EXCEPTION: main
Process: com.zionhuang.music, PID: 15225
java.lang.NullPointerException
	at com.zionhuang.music.ui.fragments.songs.ArtistSongsFragment$d.u(SourceFile:86)
	at va.a.m(Unknown Source:8)
	at lb.o0.run(Unknown Source:100)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
	Suppressed: y2.e: [a2{Cancelling}@48e00ff, Dispatchers.Main.immediate]
```

### Music version

0.4.3

### Android version

Android 10

**Comment by xmha97** [comment]
I think my problem is the same:

https://user-images.githubusercontent.com/23485114/202585429-8f973dd2-f5cb-4084-8875-9b33524c4b80.mp4

**Comment by z-huang** [comment]
Yeah, I should disable "View artist" for non-existent artists.
