### ISSUE TITLE
Unknown error when uploaded song is played

### ISSUE THREAD

**Issue by Gi-R** [z-huang/InnerTune#432]
### Checklist

- [X] I am able to reproduce the bug with the [latest DEBUG version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Play an uploaded song inside a Google account YT Music playlist after login
Song shows Unknown error instead of playing

### Expected behavior

The song should play correctly

### Actual behavior

song doesn't play, shows unknown error

### Screenshots/Screen recordings

![Senza nome](https://user-images.githubusercontent.com/117234693/202157986-0dd4dd4b-a051-407b-a285-d6eed602851c.png)

### Music version

0.4.3 (latest debug)

### Android version

Android 12

**Comment by airon90** [comment]
It happened to me too. I deleted the song from my library and readded back in order to fix it. I suppose that Youtube changed IDs of some songs (or deleted them)

**Comment by airon90** [comment]
Share your song here so that devs can fix your problem

**Comment by z-huang** [comment]
Please attach the log.

**Comment by Gi-R** [comment]
> Please attach the log.

How can I make a log file?

**Comment by Gi-R** [comment]
> Share your song here so that devs can fix your problem

I used some "test" mp3s downloaded just to try the feature, anyway I can share them if needed but i don't know if it can be useful

**Comment by z-huang** [comment]
> How can I make a log file?

`adb logcat`

**Comment by Gi-R** [comment]
[logcat.txt](https://github.com/z-huang/InnerTune/files/10047192/logcat.txt)

**Comment by Gi-R** [comment]
kotlinx.serialization.MissingFieldException: Field 'formats' is required for type with serial name 'com.zionhuang.innertube.models.response.PlayerResponse.StreamingData', but it was missing at path: $.streamingData at path: $.streamingData
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:90)
	at kotlinx.serialization.json.Json.decodeFromString(Json.kt:95)
	at io.ktor.serialization.kotlinx.KotlinxSerializationConverter.deserialize(KotlinxSerializationConverter.kt:55)
	at io.ktor.serialization.kotlinx.KotlinxSerializationConverter$deserialize$1.invokeSuspend(Unknown Source:15)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: kotlinx.serialization.MissingFieldException: Field 'formats' is required for type with serial name 'com.zionhuang.innertube.models.response.PlayerResponse.StreamingData', but it was missing at path: $.streamingData
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:90)
	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:43)
	at kotlinx.serialization.encoding.AbstractDecoder.decodeNullableSerializableElement(AbstractDecoder.kt:79)
	at com.zionhuang.innertube.models.response.PlayerResponse$$serializer.deserialize(PlayerResponse.kt:10)
	at com.zionhuang.innertube.models.response.PlayerResponse$$serializer.deserialize(PlayerResponse.kt:10)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:70)
	... 11 more
Caused by: kotlinx.serialization.MissingFieldException: Field 'formats' is required for type with serial name 'com.zionhuang.innertube.models.response.PlayerResponse.StreamingData', but it was missing
	at kotlinx.serialization.internal.PluginExceptionsKt.throwMissingFieldException(PluginExceptions.kt:20)
	at com.zionhuang.innertube.models.response.PlayerResponse$StreamingData.<init>(PlayerResponse.kt:35)
	at com.zionhuang.innertube.models.response.PlayerResponse$StreamingData$$serializer.deserialize(PlayerResponse.kt:35)
	at com.zionhuang.innertube.models.response.PlayerResponse$StreamingData$$serializer.deserialize(PlayerResponse.kt:35)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:70)
	... 16 more

This is what happens if i try to download it

**Comment by Gi-R** [comment]
Anyway, this is the Mp3 i used to test the feature
[Silent Partner - Space Walk (Youtube Premiere Countdown)[download] 60 fps.zip](https://github.com/z-huang/InnerTune/files/10047218/Silent.Partner.-.Space.Walk.Youtube.Premiere.Countdown.download.60.fps.zip)
