### ISSUE TITLE
Download error

### ISSUE THREAD

**Issue by Sumitmishra903** [z-huang/InnerTune#486]
### Checklist

- [X] I am able to reproduce the bug with the [latest DEBUG version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

After clicking on download app showed me this error
![Screenshot_2022-12-27-12-18-22-671_com zionhuang music](https://user-images.githubusercontent.com/108533035/209626643-b2c014f9-f35d-43b8-b76f-5c1f20624cbf.jpg)

### Expected behavior

Often

### Actual behavior

This happed me in the previous versions also

### Screenshots/Screen recordings

![Uploading Screenshot_2022-12-27-12-18-22-671_com.zionhuang.music.jpg…]()

### Logs

java.lang.IllegalArgumentException: Unknown URL content://downloads/my_downloads
	at android.content.ContentResolver.insert(ContentResolver.java:2170)
	at android.content.ContentResolver.insert(ContentResolver.java:2136)
	at android.app.DownloadManager.enqueue(DownloadManager.java:1646)
	at o8.e$d.u(SourceFile:905)
	at va.a.m(Unknown Source:8)
	at lb.n0.run(Unknown Source:100)
	at qb.h.run(Unknown Source:12)
	at rb.j.run(Unknown Source:2)
	at rb.a$a.run(SourceFile:82)

### Music version

0.4.4

### Android version

Android version 11

### Additional information

![Scre

**Comment by z-huang** [comment]
Do you disable the system downloader?
