### ISSUE TITLE
Nasty bug completely breaks app functionality 

### ISSUE THREAD

**Issue by meenbeese** [z-huang/InnerTune#690]
### Checklist

- [X] I am able to reproduce the bug with the [latest DEBUG version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Fresh install from GitHub
2. Go to the Home page
3. See the java.security error
4. The retry button does not work

### Expected behavior

It should be possible to use the app normally by searching and liking songs, listening to them later from the library or downloads.

### Actual behavior

I have tried multiple things that do not work: pressing on the retry button, clearing app cache, resetting app data, and reinstalling the app. The error “java.security.cert.CertPathValidatorException” persists as a banner nonetheless and completely prevents me from using the app.

### Logs

Stack trace:

javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
	at com.android.org.conscrypt.SSLUtils.toSSLHandshakeException(SSLUtils.java:363)
	at com.android.org.conscrypt.ConscryptEngine.convertException(ConscryptEngine.java:1134)
	at com.android.org.conscrypt.ConscryptEngine.readPlaintextData(ConscryptEngine.java:1089)
	at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:876)
	at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:747)
	at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:712)
	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:858)
	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.-$$Nest$mprocessDataFromSocket(Unknown Source:0)
	at com.android.org.conscrypt.ConscryptEngineSocket.doHandshake(ConscryptEngineSocket.java:241)
	at com.android.org.conscrypt.ConscryptEngineSocket.startHandshake(ConscryptEngineSocket.java:220)
	at hc.f.g(SourceFile:94)
	at hc.f.c(SourceFile:183)
	at hc.d.a(SourceFile:682)
	at hc.a.a(SourceFile:64)
	at ic.f.b(SourceFile:144)
	at fc.a.a(SourceFile:150)
	at ic.f.b(SourceFile:144)
	at ic.a.a(SourceFile:153)
	at ic.f.b(SourceFile:144)
	at ic.h.a(SourceFile:155)
	at ic.f.b(SourceFile:144)
	at hc.e.g(SourceFile:97)
	at hc.e$a.run(SourceFile:36)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
	at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:654)
	at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:613)
	at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:613)
	at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:503)
	at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:423)
	at com.android.org.conscrypt.TrustManagerImpl.getTrustedChainForServer(TrustManagerImpl.java:351)
	at android.security.net.config.NetworkSecurityTrustManager.checkServerTrusted(NetworkSecurityTrustManager.java:94)
	at android.security.net.config.RootTrustManager.checkServerTrusted(RootTrustManager.java:90)
	at com.android.org.conscrypt.ConscryptEngineSocket$2.checkServerTrusted(ConscryptEngineSocket.java:163)
	at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:256)
	at com.android.org.conscrypt.ConscryptEngine.verifyCertificateChain(ConscryptEngine.java:1638)
	at com.android.org.conscrypt.NativeCrypto.ENGINE_SSL_read_direct(Native Method)
	at com.android.org.conscrypt.NativeSsl.readDirectByteBuffer(NativeSsl.java:569)
	at com.android.org.conscrypt.ConscryptEngine.readPlaintextDataDirect(ConscryptEngine.java:1095)
	at com.android.org.conscrypt.ConscryptEngine.readPlaintextData(ConscryptEngine.java:1079)
	... 23 more
Caused by: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
	... 38 more

### InnerTune version

0.4.4

### Android version

Android 13

**Comment by z-huang** [comment]
Anyone with the same issue?

**Comment by owencz1998** [comment]
No issues on my side mate

**Comment by unknoxx** [comment]
> Anyone with the same issue?

It has lot of bugs I thought this was even abadonned

Before search results only shows on all but not on the other tabs now it doesn't even work at all I can't search for anything anymore 

Check this out:

java.lang.UnsupportedOperationException: Unknown item type
	at com.zionhuang.innertube.models.MusicResponsiveListItemRenderer.c(SourceFile:911)
	at com.zionhuang.innertube.models.SectionListRenderer$Content.a(SourceFile:228)
	at x7.h.m(SourceFile:179)
	at x7.h$j.u(Unknown Source:12)
	at va.a.m(Unknown Source:8)
	at ga.i.e(SourceFile:71)
	at ga.i.d(SourceFile:16)
	at ga.i$a.m(SourceFile:25)
	at va.a.m(Unknown Source:31)
	at ga.i.e(SourceFile:71)
	at ga.i.d(SourceFile:16)
	at ga.i$a.m(SourceFile:25)
	at va.a.m(Unknown Source:31)
	at ga.i.e(SourceFile:71)
	at ga.i.d(SourceFile:16)
	at ga.i$a.m(SourceFile:25)
	at va.a.m(Unknown Source:31)
	at ga.i.e(SourceFile:71)
	at ga.i.d(SourceFile:16)
	at ga.i$a.m(SourceFile:25)
	at va.a.m(Unknown Source:31)
	at lb.n0.run(Unknown Source:100)
	at qb.h.run(Unknown Source:12)
	at rb.j.run(Unknown Source:2)
	at rb.a$a.run(SourceFile:82)

**Comment by z-huang** [comment]
@unknoxx Are you using the latest debug build? The log shouldn't be obfuscated.

**Comment by unknoxx** [comment]
@z-huang I'm using the latest
