### ISSUE TITLE
Application crashes when songs tab is selected at search. 

### ISSUE THREAD

**Issue by fallenjedi13** [z-huang/InnerTune#784]
### Checklist

- [X] I am able to reproduce the bug with the [latest DEBUG version](https://github.com/z-huang/InnerTune/actions).
- [x] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Search for a song
2. Click on the songs tab
3. Application crashes. 

### Expected behavior

It should actually show the lists of songs. 

### Actual behavior

The application crashes instead. 

### Logs

time: 1688911995849
msg: java.lang.IllegalArgumentException: Key sVR8FlfYj30 was already used. If you are using LazyColumn/Row please make sure you provide a unique key for each item.
stacktrace: java.lang.IllegalArgumentException: Key sVR8FlfYj30 was already used. If you are using LazyColumn/Row please make sure you provide a unique key for each item.
	at i1.w$b.M0(SourceFile:159)
	at t.y.Y(SourceFile:36)
	at r.x0.a(Unknown Source:10)
	at r.k0.c(SourceFile:4)
	at r.g0.z0(SourceFile:439)
	at t.u.z0(SourceFile:26)
	at i1.x.a(SourceFile:57)
	at k1.r.B(SourceFile:37)
	at m.d$b.N(SourceFile:19)
	at i1.v.b(SourceFile:13)
	at k1.c.b(Unknown Source:14)
	at k1.x.B(SourceFile:11)
	at m.d$a.N(SourceFile:19)
	at i1.v.b(SourceFile:13)
	at k1.c.b(Unknown Source:14)
	at k1.x.B(SourceFile:11)
	at v0.n0.b(SourceFile:6)
	at k1.x.B(SourceFile:11)
	at k1.e0.F(SourceFile:9)
	at o0.h$a.a(SourceFile:64)
	at o0.a0.F(SourceFile:7)
	at androidx.activity.n.A(SourceFile:43)
	at k1.e1.a(SourceFile:116)
	at k1.d0$b.e1(SourceFile:141)
	at k1.z.N(SourceFile:17)
	at k1.h0.c(SourceFile:25)
	at k1.h0.j(SourceFile:96)
	at k1.h0.f(SourceFile:63)
	at androidx.compose.ui.platform.AndroidComposeView.a(SourceFile:14)
	at androidx.compose.ui.platform.AndroidComposeView.dispatchDraw(SourceFile:20)
	at android.view.View.draw(View.java:23228)
	at android.view.View.updateDisplayListIfDirty(View.java:22092)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
	at android.view.View.updateDisplayListIfDirty(View.java:22048)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
	at android.view.View.updateDisplayListIfDirty(View.java:22048)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
	at android.view.View.updateDisplayListIfDirty(View.java:22048)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
	at android.view.View.updateDisplayListIfDirty(View.java:22048)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:689)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:695)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:793)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:4769)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4480)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3667)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2351)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9210)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1317)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1325)
	at android.view.Choreographer.doCallbacks(Choreographer.java:983)
	at android.view.Choreographer.doFrame(Choreographer.java:915)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1300)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7929)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:859)
[Crash Log](https://stagbin.tk/6fi1pj9) 
[6fi1pj9.txt](https://github.com/z-huang/InnerTune/files/11995348/6fi1pj9.txt)

### InnerTune version

5.0

### Android version

"Android 13" 

### Additional information

Nil

**Comment by unknoxx** [comment]
Everyone got this problem the dev claims possible fix but nothing has been fixed with it 😕

**Comment by z-huang** [comment]
Fixed. Please check.

**Comment by fallenjedi13** [comment]
> Fixed. Please check.

Send to be fixed right now. Thanks a lot!
