### ISSUE TITLE
App Crashes When Navigating Between Song Timestamps

### ISSUE THREAD

**Issue by midtsveen** [z-huang/InnerTune#894]
### Checklist

- [X] I am able to reproduce the bug with the [latest DEBUG version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

I was listening to **CYA - Daybreak (Radio Edit)** on repeat **offline**, and I frequently click back from **5:26** to **3:40** as that is my favorite part of the track. However, while doing this a few times, the app occasionally crashed.

Unfortunately, I was unable to successfully reproduce this bug consistently; however, I was able to collect error logs pertaining to InnerTune. Despite my efforts, the error does not occur consistently in order for me to provide a clear reproduction path.

As a non-technical person, I have limited understanding of the code. But the logs might provide some insights for troubleshooting the issue.

### Expected behavior

The app should not crash when clicking back from a specific timestamp to another preferred timestamp.

### Actual behavior

When attempting to navigate between different parts of a song, the app crashes.

### Logs

```
type: crash
osVersion: google/bluejay/bluejay:13/TQ3A.230705.001/2023072600:user/release-keys
package: com.zionhuang.music:16
process: com.zionhuang.music
processUptime: 35020 + 367 ms
installer: dev.imranr.obtainium
 
java.util.concurrent.CancellationException
	at pb.b.get(SourceFile:1)
	at i2.a.D(Unknown Source:1)
	at m7.j.C0(SourceFile:7)
	at i5.l.b(SourceFile:654)
	at i5.j1.run(Unknown Source:12)
	at j3.c0.F(Unknown Source:25)
	at i5.c2.A0(SourceFile:97)
	at i5.c2.B0(SourceFile:9)
	at i5.n1$c.Y(SourceFile:20)
	at i5.f0.h(SourceFile:14)
	at j3.j.handleMessage(SourceFile:258)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7940)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
Caused by: kb.i1: Parent job is Cancelled; job=k1{Cancelled}@bd824bf
Caused by: java.lang.NullPointerException: null cannot be cast to non-null type android.graphics.drawable.BitmapDrawable
	at w8.a$b.j(SourceFile:65)
	at ta.a.o(Unknown Source:8)
	at qb.x.F0(Unknown Source:6)
	at kb.a.o(SourceFile:23)
	at ta.a.o(Unknown Source:31)
	at kb.o0.run(Unknown Source:105)
	at qb.l$a.run(SourceFile:4)
	at sb.j.run(Unknown Source:2)
	at sb.a$a.run(SourceFile:96)
 
```

### InnerTune version

0.5.0

### Android version

13

### Additional information

I use a Pixel 6a with GrapheneOS.

**Comment by ThatOneUnoriginal** [comment]
Been experiencing this as well. I would be just listening to a song then out of nowhere the song stops playing and the app crashes. Am using a Samsung A50 w/ the latest possible software updates available for it.

**Comment by z-huang** [comment]
Try the latest commit.

**Comment by ThatOneUnoriginal** [comment]
Wish I could but I just can't understand how to do so, and it's just leading to me getting frustrated.

**Comment by z-huang** [comment]
Download the artifact [here](https://github.com/z-huang/InnerTune/actions/runs/5915848160), unzip, and install the apk.
