### ISSUE TITLE
Artists page wouldn't load.

### ISSUE THREAD

**Issue by SandeepSinghSandhu** [z-huang/InnerTune#982]
### Checklist

- [X] I am able to reproduce the bug with the [latest DEBUG version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

It happened after using the backup and restore feature on version 0.5.1.

### Expected behavior

It should show the artists page.

### Actual behavior

It wouldn't load the artist page

### Screenshots/Screen recordings

![Screenshot_20230819_072258_InnerTune](https://github.com/z-huang/InnerTune/assets/129836673/11662fcb-54a9-4f74-a052-dedc749d8cf4)

### InnerTune version

0.5.1

### Android version

Android 13

**Comment by z-huang** [comment]
I need logs.

**Comment by owencz1998** [comment]
I'm going go try modding my old z fold 3 to get logs easier lol 😆

**Comment by Shivansh37** [comment]
Same problem happens with me

**Comment by owencz1998** [comment]
I can't do logs due to PC broke but can anyone else help this is driving me nuts 🤣🤣🤣

**Comment by owencz1998** [comment]
@z-huang sorry added to the wrong page let me know if this helps at all.

13:01:25.761 31555 31555 ₩ System.err: java.lang.NullPointerException
13:01:25.761 31555 31555 W System.err:
at com.zionhuang.innertube.pages.ArtistPage$Companion.fromMusicResponsivelistItemRenderer(ArtistPage.kt:
13:01:25.761 31555 31555 M System.err:
at com.zionhuang.innertube.pages.ArtistPageśCompanion.fromMusieshelfRendererCArtistPage.kt:42)
13:01:25.761 31555 31555 ₩ System.errs
at com.zionhuang.innertube.pages.ArtistPage$Companion.fronSectionListRendererContent(ArtistPage.kt:32)
13:01:25.761 31555 31555 ₩ System.err:
at com.zionhuang.innertube.YouTube.artist-gIAlu-s(YouTube.kt;201)
13:01:25.761 31555 31555 ₩ System.err
at com.zionhuang. innertube. VouTube$artist$i.invokesuspend(Unknown Source:15)
7 13:01:25.761 31555 31555 ₩ System.err:
at kotlin.coroutines.jvm.internal. BaseContinuationImpi.resume₩ith(ContínuationImpl.kt:33)
13:01:25.761 31555 31555 W System.err:
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
13:01:25.761 31555 31555 W System.err:
at kotlinx.coroutines.Eventloop.processUnconfinedEvent(EventLoop.common.kt:68)
13:01:25.761 31555 31555 ₩ System.err:
at kotlinx.coroutines.internal.DispatchedContinuation.resumeWíth(DispatchedContinuation.kt:345)
27 13:01:25.761 31555 31555 W System.err:
at io.ktor.util.pipeline. SuspendfunctionGun. resumeRoot₩ith(SuspendFunctionGun.kt:135)
27 13:01:25.761 31555 31555 W System.err:
at io.ktor.util.pipeline.SuspendfunctionGun. loop(SuspendFunctionGun.kt:109)
27 13:01:25.761 31555 31555 ₩ System.err:
at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:11)
27 13:01:25.761 31555 31555 ₩ System.err:
at io.ktor.util.pipeline. SuspendFunctionGun$continuation$1. resume₩íth(SuspendFunctionGun.kt:59)
27 13:01:25.761 31555 31555 W System.err:
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resume₩ith(ContinuationImpl.kt:46)
-27 13:01:25.761 31555 31555 W System.err:
at kotlinx.coroutines.DispatchedTask.run(ispatchedTask.kt:106)
-27 13:01:25.761 31555 31555 ₩ System.err:
at android.os.Handler.handleCallback(Handler. java:942)
-27 13:01:25.761 31555 31555 W System.err:
at android.os.Handler.dispatchMessage(Handler. java:99)
-27 13:01:25.761 31555 31655 W System.err:
at android. os.looper. looponce(Looper. java:226)
8-27 13:01:25.761 31555 31555 ₩ System.err:
at android.os.looper. loop(looper. java:313)
8-27 13:01:25.761 31555 31555 W System.err:
at android.app.ActivityThread.main(ActivityThread. java:8757)
8-27 13:01:25.761 31555 31555 ₩ System.err:
at java.lang,reflect. Method invoke(Native Method)
8-27 13:01:25.761 31555 31555 W System.err:
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Runtimeľnit.java:604)
98-27 13:01:25.761 31555 31555 ₩ System.err:

**Comment by z-huang** [comment]
This should happen to some artists only. Can you provide an artist that leads to the crash?

**Comment by owencz1998** [comment]
This happens to all artists 

https://github.com/z-huang/InnerTune/assets/96526481/31c116da-491b-420c-8731-6084f79fc5d6

**Comment by z-huang** [comment]
Try the latest commit.

**Comment by owencz1998** [comment]
Thanks @z-huang working perfect now dude 👌

**Comment by owencz1998** [comment]
@z-huang just noticed songs section won't load 

![Screenshot_20230829_094320_InnerTune Debug.jpg](https://github.com/z-huang/InnerTune/assets/96526481/b2f39332-cde3-4c60-822f-52db7e81f563)

**Comment by z-huang** [comment]
I need a screenshot of browsing this artist by a browser.

**Comment by owencz1998** [comment]
Sure

**Comment by owencz1998** [comment]
@z-huang 

![Screenshot_20230829_110901.jpg](https://github.com/z-huang/InnerTune/assets/96526481/66040928-0ac4-4155-9e5e-3552f1928b6f)

![Screenshot_20230829_110845.jpg](https://github.com/z-huang/InnerTune/assets/96526481/6c67e514-751b-4d98-b34e-43fd72d66810)

**Comment by z-huang** [comment]
Somehow we can't get album id from the response. If this case, we'll just set the song album to `null`. So now you should be able to see the songs, but you can't "view album" for them.
