### ISSUE TITLE
artist

### ISSUE THREAD

**Issue by Jose14** [z-huang/InnerTune#988]
### Checklist

- [X] I am able to reproduce the bug with the [latest DEBUG version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Using the go to artist option doesn't work, neither does tapping the artist name on the playback page

### Expected behavior

It doesn't work because of the error

### Actual behavior

stays charging

### InnerTune version

0.5.2

### Android version

Android 12

**Comment by z-huang** [comment]
Screenshots & logs needed.

**Comment by owencz1998** [comment]
13:01:25.761 31555 31555 ₩ System.err: java.lang.NullPointerException
13:01:25.761 31555 31555 W System.err:
at com.zionhuang.innertube.pages.ArtistPage$Companion.fromMusicResponsivelistItemRenderer(ArtistPage.kt:
13:01:25.761 31555 31555 M System.err:
at com.zionhuang.innertube.pages.ArtistPageśCompanion.fromMusieshelfRendererCArtistPage.kt:42)
13:01:25.761 31555 31555 ₩ System.errs
at com.zionhuang.innertube.pages.ArtistPage$Companion.fronSectionListRendererContent(ArtistPage.kt:32)
13:01:25.761 31555 31555 ₩ System.err:
at com.zionhuang.innertube.YouTube.artist-gIAlu-s(YouTube.kt;201)
13:01:25.761 31555 31555 ₩ System.err
at com.zionhuang. innertube. VouTube$artist$i.invokesuspend(Unknown Source:15)
7 13:01:25.761 31555 31555 ₩ System.err:
at kotlin.coroutines.jvm.internal. BaseContinuationImpi.resume₩ith(ContínuationImpl.kt:33)
13:01:25.761 31555 31555 W System.err:
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
13:01:25.761 31555 31555 W System.err:
at kotlinx.coroutines.Eventloop.processUnconfinedEvent(EventLoop.common.kt:68)
13:01:25.761 31555 31555 ₩ System.err:
at kotlinx.coroutines.internal.DispatchedContinuation.resumeWíth(DispatchedContinuation.kt:345)
27 13:01:25.761 31555 31555 W System.err:
at io.ktor.util.pipeline. SuspendfunctionGun. resumeRoot₩ith(SuspendFunctionGun.kt:135)
27 13:01:25.761 31555 31555 W System.err:
at io.ktor.util.pipeline.SuspendfunctionGun. loop(SuspendFunctionGun.kt:109)
27 13:01:25.761 31555 31555 ₩ System.err:
at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:11)
27 13:01:25.761 31555 31555 ₩ System.err:
at io.ktor.util.pipeline. SuspendFunctionGun$continuation$1. resume₩íth(SuspendFunctionGun.kt:59)
27 13:01:25.761 31555 31555 W System.err:
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resume₩ith(ContinuationImpl.kt:46)
-27 13:01:25.761 31555 31555 W System.err:
at kotlinx.coroutines.DispatchedTask.run(ispatchedTask.kt:106)
-27 13:01:25.761 31555 31555 ₩ System.err:
at android.os.Handler.handleCallback(Handler. java:942)
-27 13:01:25.761 31555 31555 W System.err:
at android.os.Handler.dispatchMessage(Handler. java:99)
-27 13:01:25.761 31555 31655 W System.err:
at android. os.looper. looponce(Looper. java:226)
8-27 13:01:25.761 31555 31555 ₩ System.err:
at android.os.looper. loop(looper. java:313)
8-27 13:01:25.761 31555 31555 W System.err:
at android.app.ActivityThread.main(ActivityThread. java:8757)
8-27 13:01:25.761 31555 31555 ₩ System.err:
at java.lang,reflect. Method invoke(Native Method)
8-27 13:01:25.761 31555 31555 W System.err:
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Runtimeľnit.java:604)
98-27 13:01:25.761 31555 31555 ₩ System.err:
at com.android.internal.os.Zygoteľnít.main(zygoteľnit.java:1067)
08-27 13:01:25.763 3075 7727 W AetivityManager: Background started FGS: Disallowed [callingPackage: com. happymod.apk; callinguid; 10471; uidstate: SVC ; i
ntent: Intent cmp=com.happymod.apk/btdownload.services.statistics.Workservice ); code:DENIÈD; tempAllowlistReason:<null>; targetsdkVersion:30; callerTarge
tSdkVersion:30; startForegroundCount:0; bindFromPackage:nul ]
08-27 13:01:25.763 3075 7727 W ActivityManager

**Comment by owencz1998** [comment]
@z-huang any of this log helpful for the search then select artist
